# Generated by Django 4.2.7 on 2026-06-17 10:29

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('restorer', '修护师'), ('reviewer', '复核员')], default='restorer', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BindingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='装订形式')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '装订形式',
                'verbose_name_plural': '装订形式',
                'db_table': 'binding_type',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.CharField(max_length=50, unique=True, verbose_name='书册编号')),
                ('review_interval_days', models.IntegerField(default=7, verbose_name='复核间隔(天)')),
                ('description', models.TextField(blank=True, verbose_name='书册描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('binding_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restoration.bindingtype', verbose_name='装订形式')),
                ('default_restorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_books', to=settings.AUTH_USER_MODEL, verbose_name='默认责任人')),
            ],
            options={
                'verbose_name': '书册',
                'verbose_name_plural': '书册',
                'db_table': 'book',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='纸张类型')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '纸张类型',
                'verbose_name_plural': '纸张类型',
                'db_table': 'paper_type',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='台位名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '处理台位',
                'verbose_name_plural': '处理台位',
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='工单编号')),
                ('status', models.CharField(choices=[('pending', '待接收'), ('processing', '处理中'), ('pending_press', '待压平'), ('pending_review', '待复核'), ('reworking', '返工中'), ('storable', '可入库'), ('paused', '暂停处理')], default='pending', max_length=20, verbose_name='状态')),
                ('review_interval_days', models.IntegerField(default=7, verbose_name='复核间隔(天)')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间')),
                ('press_started_at', models.DateTimeField(blank=True, null=True, verbose_name='压平开始时间')),
                ('press_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='压平完成时间')),
                ('review_due_at', models.DateTimeField(blank=True, null=True, verbose_name='复核到期时间')),
                ('review_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核完成时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('rework_count', models.IntegerField(default=0, verbose_name='返工次数')),
                ('pause_reason', models.TextField(blank=True, verbose_name='暂停原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoration.book', verbose_name='书册')),
                ('restorer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restoration_orders', to=settings.AUTH_USER_MODEL, verbose_name='责任人(修护师)')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restoration.station', verbose_name='处理台位')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'work_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', '待接收'), ('processing', '处理中'), ('pending_press', '待压平'), ('pending_review', '待复核'), ('reworking', '返工中'), ('storable', '可入库'), ('paused', '暂停处理')], max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('pending', '待接收'), ('processing', '处理中'), ('pending_press', '待压平'), ('pending_review', '待复核'), ('reworking', '返工中'), ('storable', '可入库'), ('paused', '暂停处理')], max_length=20, verbose_name='新状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='restoration.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '状态日志',
                'verbose_name_plural': '状态日志',
                'db_table': 'status_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatness', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], max_length=20, verbose_name='平整度')),
                ('flatness_note', models.TextField(blank=True, verbose_name='平整度说明')),
                ('page_order_correct', models.BooleanField(default=True, verbose_name='页序核对正确')),
                ('page_order_note', models.TextField(blank=True, verbose_name='页序说明')),
                ('cover_status', models.CharField(choices=[('intact', '完好'), ('minor_damage', '轻微破损'), ('major_damage', '严重破损')], max_length=20, verbose_name='封面状态')),
                ('cover_note', models.TextField(blank=True, verbose_name='封面说明')),
                ('conclusion', models.CharField(choices=[('pass', '通过'), ('rework', '返工')], max_length=20, verbose_name='最终结论')),
                ('rework_reason', models.TextField(blank=True, verbose_name='返工原因')),
                ('review_note', models.TextField(blank=True, verbose_name='复核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='复核时间')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='复核员')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='restoration.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '复核记录',
                'verbose_name_plural': '复核记录',
                'db_table': 'review_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestorationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disassembly_done', models.BooleanField(default=False, verbose_name='拆页完成')),
                ('disassembly_note', models.TextField(blank=True, verbose_name='拆页说明')),
                ('paper_repair_done', models.BooleanField(default=False, verbose_name='补纸完成')),
                ('paper_repair_note', models.TextField(blank=True, verbose_name='补纸说明')),
                ('press_done', models.BooleanField(default=False, verbose_name='压平完成')),
                ('press_level', models.CharField(blank=True, choices=[('light', '轻度'), ('medium', '中度'), ('heavy', '重度')], max_length=20, verbose_name='压平程度')),
                ('press_duration_hours', models.FloatField(blank=True, null=True, verbose_name='压平时长(小时)')),
                ('press_note', models.TextField(blank=True, verbose_name='压平说明')),
                ('binding_done', models.BooleanField(default=False, verbose_name='装订完成')),
                ('binding_note', models.TextField(blank=True, verbose_name='装订说明')),
                ('damage_description', models.TextField(blank=True, verbose_name='破损说明')),
                ('handling_note', models.TextField(blank=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('restorer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='修护师')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_records', to='restoration.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '修护记录',
                'verbose_name_plural': '修护记录',
                'db_table': 'restoration_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='default_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restoration.station', verbose_name='默认台位'),
        ),
        migrations.AddField(
            model_name='book',
            name='paper_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restoration.papertype', verbose_name='纸张类型'),
        ),
    ]
