# Generated by Django 4.2.7 on 2026-06-17 09:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('restorer', '修护师'), ('reviewer', '复核员')], default='restorer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'sys_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BindingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='装订形式')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'binding_type',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=100, unique=True, verbose_name='书册编号')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('total_pages', models.IntegerField(default=0, verbose_name='总页数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='书册描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('binding_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restoration.bindingtype', verbose_name='装订形式')),
            ],
            options={
                'db_table': 'book',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='纸张类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'paper_type',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='台位名称')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='位置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workstation',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_interval_days', models.IntegerField(default=3, verbose_name='复核间隔（天）')),
                ('status', models.CharField(choices=[('pending_receipt', '待接收'), ('processing', '处理中'), ('pending_pressing', '待压平'), ('pending_review', '待复核'), ('reworking', '返工中'), ('ready_for_storage', '可入库'), ('suspended', '暂停处理')], default='pending_receipt', max_length=30, verbose_name='状态')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间')),
                ('pressing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='压平完成时间')),
                ('review_due_at', models.DateTimeField(blank=True, null=True, verbose_name='复核到期时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='暂停时间')),
                ('rework_count', models.IntegerField(default=0, verbose_name='返工次数')),
                ('rework_reason', models.TextField(blank=True, null=True, verbose_name='最近返工原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='restoration.book', verbose_name='书册')),
                ('restorer', models.ForeignKey(limit_choices_to={'role': 'restorer'}, on_delete=django.db.models.deletion.PROTECT, related_name='restoration_orders', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'role': 'reviewer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_orders', to=settings.AUTH_USER_MODEL, verbose_name='复核员')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restoration.workstation', verbose_name='处理台位')),
            ],
            options={
                'db_table': 'work_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=30, verbose_name='目标状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='restoration.workorder', verbose_name='工单')),
            ],
            options={
                'db_table': 'status_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatness', models.TextField(verbose_name='平整度')),
                ('page_order_check', models.TextField(verbose_name='页序核对')),
                ('cover_status', models.TextField(verbose_name='封面状态')),
                ('conclusion', models.CharField(choices=[('pass', '通过'), ('rework', '返工')], max_length=20, verbose_name='最终结论')),
                ('rework_reason', models.TextField(blank=True, null=True, verbose_name='返工原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'reviewer'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='复核员')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='restoration.workorder', verbose_name='工单')),
            ],
            options={
                'db_table': 'review_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestorationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disassembly_pages', models.TextField(blank=True, null=True, verbose_name='拆页情况')),
                ('paper_repair', models.TextField(blank=True, null=True, verbose_name='补纸情况')),
                ('pressing', models.TextField(blank=True, null=True, verbose_name='压平情况')),
                ('binding', models.TextField(blank=True, null=True, verbose_name='装订情况')),
                ('damage_description', models.TextField(blank=True, null=True, verbose_name='破损说明')),
                ('processing_notes', models.TextField(blank=True, null=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restorer', models.ForeignKey(limit_choices_to={'role': 'restorer'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='修护师')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_records', to='restoration.workorder', verbose_name='工单')),
            ],
            options={
                'db_table': 'restoration_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='paper_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restoration.papertype', verbose_name='纸张类型'),
        ),
    ]
