# Generated by Django 4.2.7 on 2026-06-17 08:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('restorer', '修护师'), ('reviewer', '复核员')], default='restorer', max_length=20, verbose_name='角色')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BookVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='书册编号')),
                ('paper_type', models.CharField(max_length=64, verbose_name='纸张类型')),
                ('binding_form', models.CharField(max_length=64, verbose_name='装订形式')),
                ('station', models.CharField(blank=True, default='', max_length=64, verbose_name='处理台位')),
                ('review_interval_days', models.PositiveIntegerField(default=7, verbose_name='复核间隔(天)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_books', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '书册',
                'verbose_name_plural': '书册',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待接收'), ('processing', '处理中'), ('pending_pressing', '待压平'), ('pending_review', '待复核'), ('rework', '返工中'), ('can_store', '可入库'), ('suspended', '暂停处理')], default='pending', max_length=30, verbose_name='状态')),
                ('page_removal', models.TextField(blank=True, default='', verbose_name='拆页说明')),
                ('paper_repair', models.TextField(blank=True, default='', verbose_name='补纸说明')),
                ('pressing', models.TextField(blank=True, default='', verbose_name='压平说明')),
                ('binding', models.TextField(blank=True, default='', verbose_name='装订说明')),
                ('damage_description', models.TextField(blank=True, default='', verbose_name='破损说明')),
                ('processing_notes', models.TextField(blank=True, default='', verbose_name='处理备注')),
                ('rework_reason', models.TextField(blank=True, default='', verbose_name='返工原因')),
                ('rework_count', models.PositiveIntegerField(default=0, verbose_name='返工次数')),
                ('pressing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='压平完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='restoration.bookvolume', verbose_name='书册')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_orders', to=settings.AUTH_USER_MODEL, verbose_name='修护师')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatness', models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格')], max_length=20, verbose_name='平整度')),
                ('page_order_check', models.CharField(choices=[('correct', '正确'), ('incorrect', '不正确')], max_length=20, verbose_name='页序核对')),
                ('cover_status', models.CharField(choices=[('intact', '完好'), ('damaged', '损坏')], max_length=20, verbose_name='封面状态')),
                ('conclusion', models.CharField(choices=[('pass', '通过'), ('rework', '返工')], max_length=20, verbose_name='最终结论')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='复核时间')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='复核员')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restoration.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '复核记录',
                'verbose_name_plural': '复核记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('review_overdue', '复核超期'), ('high_rework', '同纸张返工偏多'), ('no_review_after_pressing', '压平后无复核'), ('abnormal_cycle', '处理周期异常')], max_length=40, verbose_name='预警类型')),
                ('message', models.TextField(verbose_name='预警信息')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='restoration.workorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '预警',
                'verbose_name_plural': '预警',
                'ordering': ['-created_at'],
            },
        ),
    ]
